wip

diff --git a/template/x b/template/x
--- a/template/x
+++ b/template/x
@@ -1,15 +1,15 @@
 #!/bin/bash
+# https://xscripts.sh - XScripts To Rule Them All
+# Version: 0.1.0
 
 readonly XSCRIPTS_DIR="$(dirname "$0")/.xscripts"
 readonly IS_DOCKER_COMPOSE_ENVIRONMENT=$((test -f ./docker-compose.yml || test -f ./docker-compose.yaml) && echo true || echo false)
 readonly IS_INSIDE_DOCKER_CONTAINER=$((test -f /.dockerenv) && echo true || echo false)
+declare -a COMMANDS
 
-# source files that start with underscore
-for file in "$XSCRIPTS_DIR"/*; do
-  if [[ "$(basename "$file")" == _* ]]; then
-    source $file
-  fi
-done
+source $XSCRIPTS_DIR/__xscripts
+
+::load_libraries_and_commands
 
 # figure out the environment
 if [ "$IS_DOCKER_COMPOSE_ENVIRONMENT" = true ]; then
@@ -23,18 +23,24 @@ if [ -z "$1" ]; then
   exit 0
 fi
 
-# loop through arguments checking the requested scripts
-for REQUESTED_SCRIPT in "$@"; do
-  REQUESTED_SCRIPT_PATH="$XSCRIPTS_DIR/$REQUESTED_SCRIPT"
-  if [ ! -f "$REQUESTED_SCRIPT_PATH" ]; then
-    echo "Script not found: $REQUESTED_SCRIPT_PATH"
-    print_help
-    exit 1
-  fi
-done
+REQUESTED_COMMAND="$1"
 
-# run requested scripts
-for REQUESTED_SCRIPT in "$@"; do
-  REQUESTED_SCRIPT_PATH="$XSCRIPTS_DIR/$REQUESTED_SCRIPT"
-  source "$REQUESTED_SCRIPT_PATH"
-done
+if ($REQUESTED_COMMAND == "make"); then
+  ::make_command $2
+
+  exit 0
+fi
+
+# get the requested script from COMMANDS
+REQUESTED_SCRIPT=$(echo ${COMMANDS[@]} | tr ' ' '\n' | grep "$REQUESTED_COMMAND" | cut -d "=" -f 2)
+REQUESTED_SCRIPT_PATH="$XSCRIPTS_DIR/$REQUESTED_SCRIPT"
+
+if [ ! -f "$REQUESTED_SCRIPT_PATH" ]; then
+  echo "Script not found: $REQUESTED_SCRIPT_PATH"
+  print_help
+  exit 1
+fi
+
+source $REQUESTED_SCRIPT_PATH
+
+exit 0
